-- Phase 1: application-owned data only. JSON remains serialized TEXT.
CREATE TABLE settings_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    settings TEXT NOT NULL,
    UNIQUE (user_id, name)
);

CREATE TABLE bulk_batches (
    id TEXT PRIMARY KEY,
    metadata TEXT NOT NULL
);

CREATE TABLE bulk_scrambles (
    batch_id TEXT NOT NULL REFERENCES bulk_batches(id),
    line_number INTEGER NOT NULL,
    alg_count INTEGER,
    result TEXT NOT NULL,
    PRIMARY KEY (batch_id, line_number)
);

CREATE INDEX bulk_alg_count ON bulk_scrambles (batch_id, alg_count, line_number);
